### ISSUE TITLE
Any contributing guidelines?

### ISSUE THREAD

**Issue by nlhnt** [dernasherbrezon/jradio#7]
Hello,
I am having a hard time using Python in GNU Radio, I have to pretty much rewrite any abandoned CGRAN module into Python3.
Don't get me wrong I love Python, but the software created with it is dependant on the interpreter and the result is that many great modules, which for various reasons had been abandoned now don't work.

I don't want to hate on the choice of Python, that's the main tool we use at work, but creating projects as big as GNURadio using Python as the main gluecode language just lead (in my opinion) to GNURadio being really hurt. Especially with Python2 reaching the end of life. Most people had written their modules for GNURadio 3.7 or lower which didn't allow the useage of Python3 so GNURadio ended up in a weird spot where many of modules are not compatible with the current version. What's worse, it is really hard to install GNURadio 3.7 on modern linux distributions, because many of them removed Python2 from their repositories almost entirely.

Anyway I was thinking of doing something similar in Java, but seeing as there is a project in here already, I wanted to know wether or not you predict any guidelines for others to join in on the work to be done?

Have you considered writing Java bindings GNU Radio?
I am asking because some modules (f.e. ieee-802-11) require SIMD optimization and I am not sure if that's available in Java.
I'd be happy if GNURadio used a combination of Java and C/C++ instead of Python and C/C++.

**Comment by dernasherbrezon** [comment]
There is no "contributing guidelines" per se. We can discuss any new feature here and what to do next.

There are several hiccups with jradio bindings to GNU Radio:

1. jradio doesn't use buffers between the blocks. So this will immediately make it hard to write JNI wrappers for GNU Radio.
2. Also GNU Radio blocks are connected to each other while in jradio blocks are stacked into each other. I.e. constructors are different
3. Any SIMD optimization gains might be lost when converting the data into JNI and back.
4. GNU Radio blocks can change their interface and we will constantly stay behind them. So IMHO java bindings better to keep in GNU Radio repository.

jradio designed to be binary compatible with GNU Radio blocks, so the only drawback of using pure java is SIMD performance optimization. 

I thought about this during long winter nights and came to some conclusions:

1. Performance is not needed for some use cases. For example, there is no need to demodulate satellite signal in realtime if TX not supposed to be.
2. Performance is enough for some use cases. Some amateur protocols on 1200baud or 9600baud can be demodulated and decoded in realtime.
3. Some high performant blocks like FrequencyXlating or decimation can be implemented externally as part of a common demodulator. For example, AFSK and FSK demodulators can be implemented in C++ and jradio can work on much lower rate from these demodulators.

**Comment by dernasherbrezon** [comment]
Added contributing section to the readme: https://github.com/dernasherbrezon/jradio#contributing
